### ISSUE TITLE
sprout-osx-apps::go line 13 errors during run

### ISSUE THREAD

**Issue by jim80net** [pivotal-sprout/sprout-osx-apps#257]
The money: 

```
STDERR: # golang.org/x/tools/go/types
    Users/pivotal/go/src/golang.org/x/tools/go/types/builtins.go:13: import /Users/pivotal/go/pkg/darwin_amd64/golang.org/x/tools/go/ast/astutil.a: object is [darwin amd64 go1.4 X:precisestack] expected [darwin amd64 go1.4.1 X:precisestack]
```
What does this mean?  

Here is the full error from LOG_LEVEL=debug:

```
2015-02-23T14:36:33-08:00] DEBUG: template[/Users/pivotal/.bash_it/custom/go.bash] checksumming file at /Users/pivotal/.bash_it/custom/go.bash.
[2015-02-23T14:36:33-08:00] DEBUG: calculating checksum of /tmp/chef-rendered-template20150223-62471-1avl9ex to compare with 2b01421cda80b2d1ff68c9f373660b99e7fc651eb94ecefc0d2f38c44ec886a5
[2015-02-23T14:36:33-08:00] DEBUG: found target_mode == nil, so no mode was specified on resource, not managing mode
[2015-02-23T14:36:33-08:00] DEBUG: found target_uid == current_uid, not updating owner
[2015-02-23T14:36:33-08:00] DEBUG: found target_gid == nil, so no group was specified on resource, not managing group
 (up to date)
  * execute[/usr/local/bin/go get golang.org/x/tools/cmd/godoc] action run[2015-02-23T14:36:33-08:00] INFO: Processing execute[/usr/local/bin/go get golang.org/x/tools/cmd/godoc] action run (sprout-osx-apps::go line 13)
# golang.org/x/tools/go/types
Users/pivotal/go/src/golang.org/x/tools/go/types/builtins.go:13: import /Users/pivotal/go/pkg/darwin_amd64/golang.org/x/tools/go/ast/astutil.a: object is [darwin amd64 go1.4 X:precisestack] expected [darwin amd64 go1.4.1 X:precisestack]


    ================================================================================
    Error executing action `run` on resource 'execute[/usr/local/bin/go get golang.org/x/tools/cmd/godoc]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '2'
    ---- Begin output of /usr/local/bin/go get golang.org/x/tools/cmd/godoc ----
    STDOUT:
    STDERR: # golang.org/x/tools/go/types
    Users/pivotal/go/src/golang.org/x/tools/go/types/builtins.go:13: import /Users/pivotal/go/pkg/darwin_amd64/golang.org/x/tools/go/ast/astutil.a: object is [darwin amd64 go1.4 X:precisestack] expected [darwin amd64 go1.4.1 X:precisestack]
    ---- End output of /usr/local/bin/go get golang.org/x/tools/cmd/godoc ----
    Ran /usr/local/bin/go get golang.org/x/tools/cmd/godoc returned 2

    Resource Declaration:
    ---------------------
    # In /Users/pivotal/workspace/sprout-wrap/.librarian/chef/cookbooks/sprout-osx-apps/recipes/go.rb

     13: execute '/usr/local/bin/go get golang.org/x/tools/cmd/godoc' do
     14:   environment('GOPATH' => File.join(node['sprout']['home'], 'go'))
     15:   user node['sprout']['user']
     16: end

    Compiled Resource:
    ------------------
    # Declared in /Users/pivotal/workspace/sprout-wrap/.librarian/chef/cookbooks/sprout-osx-apps/recipes/go.rb:13:in `from_file'

    execute("/usr/local/bin/go get golang.org/x/tools/cmd/godoc") do
      action "run"
      retries 0
      retry_delay 2
      guard_interpreter :default
      command "/usr/local/bin/go get golang.org/x/tools/cmd/godoc"
      backup 5
      environment {"GOPATH"=>"/Users/pivotal/go"}
      returns 0
      user "pivotal"
      cookbook_name :"sprout-osx-apps"
      recipe_name "go"
    end

[2015-02-23T14:36:34-08:00] INFO: Running queued delayed notifications before re-raising exception
[2015-02-23T14:36:34-08:00] INFO: execute[TimeMachine should NOT appear in the status bar] sending run action to execute[restart SystemUIServer] (delayed)
Recipe: sprout-osx-settings::timemachine
  * execute[restart SystemUIServer] action run[2015-02-23T14:36:34-08:00] INFO: Processing execute[restart SystemUIServer] action run (sprout-osx-settings::timemachine line 17)
[2015-02-23T14:36:34-08:00] INFO: execute[restart SystemUIServer] ran successfully

    - execute killall -HUP SystemUIServer
[2015-02-23T14:36:34-08:00] DEBUG: Re-raising exception: Mixlib::ShellOut::ShellCommandFailed - execute[/usr/local/bin/go get golang.org/x/tools/cmd/godoc] (sprout-osx-apps::go line 13) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '2'
---- Begin output of /usr/local/bin/go get golang.org/x/tools/cmd/godoc ----
STDOUT:
STDERR: # golang.org/x/tools/go/types
Users/pivotal/go/src/golang.org/x/tools/go/types/builtins.go:13: import /Users/pivotal/go/pkg/darwin_amd64/golang.org/x/tools/go/ast/astutil.a: object is [darwin amd64 go1.4 X:precisestack] expected [darwin amd64 go1.4.1 X:precisestack]
---- End output of /usr/local/bin/go get golang.org/x/tools/cmd/godoc ----
Ran /usr/local/bin/go get golang.org/x/tools/cmd/godoc returned 2
/Users/pivotal/.gem/ruby/2.1.3/gems/mixlib-shellout-1.6.1/lib/mixlib/shellout.rb:272:in `invalid!'
  /Users/pivotal/.gem/ruby/2.1.3/gems/mixlib-shellout-1.6.1/lib/mixlib/shellout.rb:259:in `error!'
  /Users/pivotal/.gem/ruby/2.1.3/gems/chef-11.16.4/lib/chef/mixin/shell_out.rb:43:in `shell_out!'
  /Users/pivotal/.gem/ruby/2.1.3/gems/chef-11.16.4/lib/chef/provider/execute.rb:60:in `block in action_run'
  /Users/pivotal/.gem/ruby/2.1.3/gems/chef-11.16.4/lib/chef/mixin/why_run.rb:52:in `call'
  /Users/pivotal/.gem/ruby/2.1.3/gems/chef-11.16.4/lib/chef/mixin/why_run.rb:52:in `add_action'
  /Users/pivotal/.gem/ruby/2.1.3/gems/chef-11.16.4/lib/chef/provider.rb:156:in `converge_by'
  /Users/pivotal/.gem/ruby/2.1.3/gems/chef-11.16.4/lib/chef/provider/execute.rb:59:in `action_run'
  /Users/pivotal/.gem/ruby/2.1.3/gems/chef-11.16.4/lib/chef/provider.rb:121:in `run_action'
  /Users/pivotal/.gem/ruby/2.1.3/gems/chef-11.16.4/lib/chef/resource.rb:648:in `run_action'
  /Users/pivotal/.gem/ruby/2.1.3/gems/chef-11.16.4/lib/chef/runner.rb:49:in `run_action'
  /Users/pivotal/.gem/ruby/2.1.3/gems/chef-11.16.4/lib/chef/runner.rb:81:in `block (2 levels) in converge'
  /Users/pivotal/.gem/ruby/2.1.3/gems/chef-11.16.4/lib/chef/runner.rb:81:in `each'
  /Users/pivotal/.gem/ruby/2.1.3/gems/chef-11.16.4/lib/chef/runner.rb:81:in `block in converge'
  /Users/pivotal/.gem/ruby/2.1.3/gems/chef-11.16.4/lib/chef/resource_collection.rb:98:in `block in execute_each_resource'
  /Users/pivotal/.gem/ruby/2.1.3/gems/chef-11.16.4/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
  /Users/pivotal/.gem/ruby/2.1.3/gems/chef-11.16.4/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
  /Users/pivotal/.gem/ruby/2.1.3/gems/chef-11.16.4/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
  /Users/pivotal/.gem/ruby/2.1.3/gems/chef-11.16.4/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
  /Users/pivotal/.gem/ruby/2.1.3/gems/chef-11.16.4/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
  /Users/pivotal/.gem/ruby/2.1.3/gems/chef-11.16.4/lib/chef/resource_collection.rb:96:in `execute_each_resource'
  /Users/pivotal/.gem/ruby/2.1.3/gems/chef-11.16.4/lib/chef/runner.rb:80:in `converge'
  /Users/pivotal/.gem/ruby/2.1.3/gems/chef-11.16.4/lib/chef/client.rb:345:in `converge'
  /Users/pivotal/.gem/ruby/2.1.3/gems/chef-11.16.4/lib/chef/client.rb:431:in `do_run'
  /Users/pivotal/.gem/ruby/2.1.3/gems/chef-11.16.4/lib/chef/client.rb:213:in `block in run'
  /Users/pivotal/.gem/ruby/2.1.3/gems/chef-11.16.4/lib/chef/client.rb:207:in `fork'
  /Users/pivotal/.gem/ruby/2.1.3/gems/chef-11.16.4/lib/chef/client.rb:207:in `run'
  /Users/pivotal/.gem/ruby/2.1.3/gems/chef-11.16.4/lib/chef/application.rb:236:in `run_chef_client'
  /Users/pivotal/.gem/ruby/2.1.3/gems/chef-11.16.4/lib/chef/application/solo.rb:226:in `block in run_application'
  /Users/pivotal/.gem/ruby/2.1.3/gems/chef-11.16.4/lib/chef/application/solo.rb:218:in `loop'
  /Users/pivotal/.gem/ruby/2.1.3/gems/chef-11.16.4/lib/chef/application/solo.rb:218:in `run_application'
  /Users/pivotal/.gem/ruby/2.1.3/gems/chef-11.16.4/lib/chef/application.rb:55:in `run'
  /Users/pivotal/.gem/ruby/2.1.3/gems/chef-11.16.4/bin/chef-solo:25:in `<top (required)>'
  /Users/pivotal/.gem/ruby/2.1.3/bin/chef-solo:23:in `load'
  /Users/pivotal/.gem/ruby/2.1.3/bin/chef-solo:23:in `<main>'

Running handlers:
[2015-02-23T14:36:34-08:00] ERROR: Running exception handlers
Running handlers complete
[2015-02-23T14:36:34-08:00] ERROR: Exception handlers complete
[2015-02-23T14:36:34-08:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2015-02-23T14:36:34-08:00] DEBUG: Mixlib::ShellOut::ShellCommandFailed: execute[/usr/local/bin/go get golang.org/x/tools/cmd/godoc] (sprout-osx-apps::go line 13) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '2'
---- Begin output of /usr/local/bin/go get golang.org/x/tools/cmd/godoc ----
STDOUT:
STDERR: # golang.org/x/tools/go/types
Users/pivotal/go/src/golang.org/x/tools/go/types/builtins.go:13: import /Users/pivotal/go/pkg/darwin_amd64/golang.org/x/tools/go/ast/astutil.a: object is [darwin amd64 go1.4 X:precisestack] expected [darwin amd64 go1.4.1 X:precisestack]
---- End output of /usr/local/bin/go get golang.org/x/tools/cmd/godoc ----
Ran /usr/local/bin/go get golang.org/x/tools/cmd/godoc returned 2
/Users/pivotal/.gem/ruby/2.1.3/gems/mixlib-shellout-1.6.1/lib/mixlib/shellout.rb:272:in `invalid!'
/Users/pivotal/.gem/ruby/2.1.3/gems/mixlib-shellout-1.6.1/lib/mixlib/shellout.rb:259:in `error!'
/Users/pivotal/.gem/ruby/2.1.3/gems/chef-11.16.4/lib/chef/mixin/shell_out.rb:43:in `shell_out!'
/Users/pivotal/.gem/ruby/2.1.3/gems/chef-11.16.4/lib/chef/provider/execute.rb:60:in `block in action_run'
/Users/pivotal/.gem/ruby/2.1.3/gems/chef-11.16.4/lib/chef/mixin/why_run.rb:52:in `call'
/Users/pivotal/.gem/ruby/2.1.3/gems/chef-11.16.4/lib/chef/mixin/why_run.rb:52:in `add_action'
/Users/pivotal/.gem/ruby/2.1.3/gems/chef-11.16.4/lib/chef/provider.rb:156:in `converge_by'
/Users/pivotal/.gem/ruby/2.1.3/gems/chef-11.16.4/lib/chef/provider/execute.rb:59:in `action_run'
/Users/pivotal/.gem/ruby/2.1.3/gems/chef-11.16.4/lib/chef/provider.rb:121:in `run_action'
/Users/pivotal/.gem/ruby/2.1.3/gems/chef-11.16.4/lib/chef/resource.rb:648:in `run_action'
/Users/pivotal/.gem/ruby/2.1.3/gems/chef-11.16.4/lib/chef/runner.rb:49:in `run_action'
/Users/pivotal/.gem/ruby/2.1.3/gems/chef-11.16.4/lib/chef/runner.rb:81:in `block (2 levels) in converge'
/Users/pivotal/.gem/ruby/2.1.3/gems/chef-11.16.4/lib/chef/runner.rb:81:in `each'
/Users/pivotal/.gem/ruby/2.1.3/gems/chef-11.16.4/lib/chef/runner.rb:81:in `block in converge'
/Users/pivotal/.gem/ruby/2.1.3/gems/chef-11.16.4/lib/chef/resource_collection.rb:98:in `block in execute_each_resource'
/Users/pivotal/.gem/ruby/2.1.3/gems/chef-11.16.4/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/Users/pivotal/.gem/ruby/2.1.3/gems/chef-11.16.4/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/Users/pivotal/.gem/ruby/2.1.3/gems/chef-11.16.4/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/Users/pivotal/.gem/ruby/2.1.3/gems/chef-11.16.4/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/Users/pivotal/.gem/ruby/2.1.3/gems/chef-11.16.4/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/Users/pivotal/.gem/ruby/2.1.3/gems/chef-11.16.4/lib/chef/resource_collection.rb:96:in `execute_each_resource'
/Users/pivotal/.gem/ruby/2.1.3/gems/chef-11.16.4/lib/chef/runner.rb:80:in `converge'
/Users/pivotal/.gem/ruby/2.1.3/gems/chef-11.16.4/lib/chef/client.rb:345:in `converge'
/Users/pivotal/.gem/ruby/2.1.3/gems/chef-11.16.4/lib/chef/client.rb:431:in `do_run'
/Users/pivotal/.gem/ruby/2.1.3/gems/chef-11.16.4/lib/chef/client.rb:213:in `block in run'
/Users/pivotal/.gem/ruby/2.1.3/gems/chef-11.16.4/lib/chef/client.rb:207:in `fork'
/Users/pivotal/.gem/ruby/2.1.3/gems/chef-11.16.4/lib/chef/client.rb:207:in `run'
/Users/pivotal/.gem/ruby/2.1.3/gems/chef-11.16.4/lib/chef/application.rb:236:in `run_chef_client'
/Users/pivotal/.gem/ruby/2.1.3/gems/chef-11.16.4/lib/chef/application/solo.rb:226:in `block in run_application'
/Users/pivotal/.gem/ruby/2.1.3/gems/chef-11.16.4/lib/chef/application/solo.rb:218:in `loop'
/Users/pivotal/.gem/ruby/2.1.3/gems/chef-11.16.4/lib/chef/application/solo.rb:218:in `run_application'
/Users/pivotal/.gem/ruby/2.1.3/gems/chef-11.16.4/lib/chef/application.rb:55:in `run'
/Users/pivotal/.gem/ruby/2.1.3/gems/chef-11.16.4/bin/chef-solo:25:in `<top (required)>'
/Users/pivotal/.gem/ruby/2.1.3/bin/chef-solo:23:in `load'
/Users/pivotal/.gem/ruby/2.1.3/bin/chef-solo:23:in `<main>'
Chef Client failed. 65 resources updated in 27.572424 seconds
[2015-02-23T14:36:34-08:00] ERROR: execute[/usr/local/bin/go get golang.org/x/tools/cmd/godoc] (sprout-osx-apps::go line 13) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '2'
---- Begin output of /usr/local/bin/go get golang.org/x/tools/cmd/godoc ----
STDOUT:
STDERR: # golang.org/x/tools/go/types
Users/pivotal/go/src/golang.org/x/tools/go/types/builtins.go:13: import /Users/pivotal/go/pkg/darwin_amd64/golang.org/x/tools/go/ast/astutil.a: object is [darwin amd64 go1.4 X:precisestack] expected [darwin amd64 go1.4.1 X:precisestack]
---- End output of /usr/local/bin/go get golang.org/x/tools/cmd/godoc ----
Ran /usr/local/bin/go get golang.org/x/tools/cmd/godoc returned 2
[2015-02-23T14:36:34-08:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by adamstegman** [comment]
It looks like the version of Go changed and that didn't get recompiled.

**Comment by aramprice** [comment]
That's been my experience. I had this happen a few months back, removing $GOPATH/pkg/ and $GOPATH/bin/ seemed to resolve it
